feat: Add about page to fable test app
cds-snc/gcds-examples pull request #22
Opened 2024-09-05 14:20 UTC by ethanWallace

# Summary | Résumé

Add about page from [figma prototype]([Figma prototype](https://www.figma.com/proto/672zNYNzI3NqotZCccZjXT/Holidays-app?node-id=27-1233&t=yfEWqC9LQeFCt0Ic-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=13%3A824)).

2024-09-05 22:39 UTC, melaniebmn commented on fable-test-app/src/pages/About.tsx
> +import githubImage from '../assets/github.png';
If you add the images in the `public` folder instead of `src/assets`, you don't have to import them.

2024-09-05 22:40 UTC, melaniebmn requested changes
A small comment about the image import, it looks good otherwise.

2024-09-06 16:24 UTC, melaniebmn commented on fable-test-app/src/pages/About.tsx
> +      </GcdsGrid>
Sorry, another comment :D Should we create internal components for GcdsGrid and GcdsCard?

2024-09-06 16:24 UTC, melaniebmn requested changes
Sorry, should have flagged this yesterday

2024-09-09 22:25 UTC, daine approved these changes
LGTM

2024-09-10 04:54 UTC, melaniebmn approved these changes
LGTM

2024-09-10 18:39 UTC, merged